@startuml WiapMR_BasicStructure

PlaceableObject - SnapPoint

class PlaceableObject{
    boolean isSnapping;
    SnapPoint snappedTo;
    void snapTo(SnapPoint snapPoint);
}

class SnapPoint {
    List<SnapPoint> connectedSnapPoints;
    PlaceableObject placeableObject;
    GameBoard gameBoard;
}

SnapPoint "0.." - GameBoard

abstract class GameBoard{
    //Gamelogic
    List<SnapPoint> snapPoints;
    List<SnapPoint> getSnapPoints();
}
@enduml